<?php

namespace Database\Seeders;

use App\Models\CampoDinamico;
use App\Models\Categoria;
use App\Models\TipoItem;
use Illuminate\Database\Seeder;

class EstructuraCategoriasSeeder extends Seeder
{
    // Formato por campo: [nombre, tipo, opciones?, placeholder?]
    // tipo: select | texto | textarea
    private const ELEMENTOS = [
        'A1' => [
            'nombre' => 'Amoblamiento y útiles',
            'elementos' => [
                'Armario' => [
                    ['Material', 'select', ['Madera', 'Melamina', 'Metal', 'MDF', 'Aglomerado', 'Plástico'], 'Madera, melamina, metal'],
                    ['Color', 'texto'],
                    ['Medidas', 'texto', null, 'Alto-Ancho-Largo'],
                    ['Características', 'texto', null, 'Puertas, cajones, vidrio'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Biblioteca' => [
                    ['Material', 'select', ['Madera', 'Melamina', 'Metal', 'MDF', 'Aglomerado', 'Plástico'], 'Madera, melamina, metal'],
                    ['Color', 'texto'],
                    ['Medidas', 'texto', null, 'Alto-Ancho-Largo'],
                    ['Características', 'texto', null, 'Puertas, cajones, vidrio'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Escritorio' => [
                    ['Material', 'select', ['Madera', 'Melamina', 'Metal', 'MDF', 'Aglomerado', 'Plástico'], 'Madera, melamina, metal'],
                    ['Color', 'texto'],
                    ['Medidas', 'texto', null, 'Alto-Ancho-Largo'],
                    ['Características', 'texto', null, 'Puertas, cajones, vidrio'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Mesa' => [
                    ['Material', 'select', ['Madera', 'Melamina', 'Metal', 'MDF', 'Aglomerado', 'Plástico', 'Vidrio'], 'Madera, melamina, metal'],
                    ['Color', 'texto'],
                    ['Medidas', 'texto', null, 'Alto-Ancho-Largo'],
                    ['Características', 'texto', null, 'Puertas, cajones, vidrio'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Modular' => [
                    ['Material', 'select', ['Madera', 'Melamina', 'Metal', 'MDF', 'Aglomerado', 'Plástico'], 'Madera, melamina, metal'],
                    ['Color', 'texto'],
                    ['Medidas', 'texto', null, 'Alto-Ancho-Largo'],
                    ['Características', 'texto', null, 'Puertas, cajones, vidrio'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Perchero' => [
                    ['Material', 'select', ['Madera', 'Melamina', 'Metal', 'MDF', 'Aglomerado', 'Plástico'], 'Madera, melamina, metal'],
                    ['Color', 'texto'],
                    ['Medidas', 'texto', null, 'Alto-Ancho-Largo'],
                    ['Características', 'texto', null, 'Puertas, cajones, vidrio'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Pizarron' => [
                    ['Material', 'select', ['Madera', 'Melamina', 'Metal', 'MDF', 'Aglomerado', 'Plástico'], 'Madera, melamina, metal'],
                    ['Color', 'texto'],
                    ['Medidas', 'texto', null, 'Alto-Ancho-Largo'],
                    ['Características', 'texto', null, 'Puertas, cajones, vidrio'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Silla' => [
                    ['Material', 'select', ['Madera', 'Melamina', 'Metal', 'MDF', 'Aglomerado', 'Plástico'], 'Madera, melamina, metal'],
                    ['Color', 'texto'],
                    ['Medidas', 'texto', null, 'Alto-Ancho-Largo'],
                    ['Características', 'texto', null, 'Puertas, cajones, vidrio'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Silla ejecutiva' => [
                    ['Material', 'select', ['Madera', 'Melamina', 'Metal', 'MDF', 'Aglomerado', 'Plástico'], 'Madera, melamina, metal'],
                    ['Color', 'texto'],
                    ['Medidas', 'texto', null, 'Alto-Ancho-Largo'],
                    ['Características', 'texto', null, 'Puertas, cajones, vidrio'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Sillón' => [
                    ['Material', 'select', ['Madera', 'Melamina', 'Metal', 'MDF', 'Aglomerado', 'Plástico'], 'Madera, melamina, metal'],
                    ['Color', 'texto'],
                    ['Medidas', 'texto', null, 'Alto-Ancho-Largo'],
                    ['Características', 'texto', null, 'Puertas, cajones, vidrio'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
            ],
        ],
        'A2' => [
            'nombre' => 'Artefactos eléctricos',
            'elementos' => [
                'Aire acondicionado' => [
                    ['Marca', 'texto', null, 'Samsung, LG, etc.'],
                    ['Modelo', 'texto', null, 'ABC123'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Capacidad (BTU)', 'texto', null, '10000'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Ventilador' => [
                    ['Marca', 'texto', null, 'Samsung, LG, etc.'],
                    ['Modelo', 'texto', null, 'XYZ789'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Capacidad (RPM)', 'texto', null, '1200'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Calefactor' => [
                    ['Marca', 'texto', null, 'Samsung, LG, etc.'],
                    ['Modelo', 'texto', null, 'DEF456'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Capacidad (W)', 'texto', null, '1500'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Estufa' => [
                    ['Marca', 'texto', null, 'Samsung, LG, etc.'],
                    ['Modelo', 'texto', null, 'GHI789'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Capacidad (W)', 'texto', null, '2000'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Plafones' => [
                    ['Marca', 'texto', null, 'Samsung, LG, etc.'],
                    ['Modelo', 'texto', null, 'JKL012'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Capacidad (W)', 'texto', null, '500'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Heladeras' => [
                    ['Marca', 'texto', null, 'Samsung, LG, etc.'],
                    ['Modelo', 'texto', null, 'MNO345'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Capacidad (L)', 'texto', null, '200'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Freezers' => [
                    ['Marca', 'texto', null, 'Samsung, LG, etc.'],
                    ['Modelo', 'texto', null, 'PQR678'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Capacidad (L)', 'texto', null, '300'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
            ],
        ],
        'A3' => [
            'nombre' => 'Equipo de radiocomunicación, telefonía e informática',
            'elementos' => [
                'Cámara de seguridad' => [
                    ['Marca', 'texto', null, 'Hikvision, Dahua, etc.'],
                    ['Modelo', 'texto', null, 'DS-2CD2043G0-I'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Conectividad', 'select', ['IP', 'Cableada', 'Ambas']],
                    ['Tipo', 'select', ['Domo', 'Bala', 'Caja']],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Computadora de escritorio' => [
                    ['Marca', 'texto', null, 'Dell, HP, etc.'],
                    ['Modelo', 'texto', null, 'OptiPlex 7070'],
                    ['Número de serie', 'texto', null, 'SN123456, no visible'],
                    ['Procesador', 'texto', null, 'Intel i5'],
                    ['RAM', 'texto', null, '8GB'],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Computadora portátil' => [
                    ['Marca', 'texto', null, 'Dell, HP, etc.'],
                    ['Modelo', 'texto', null, 'Latitude 5400'],
                    ['Número de serie', 'texto', null, 'SN123456, no visible'],
                    ['Procesador', 'texto', null, 'Intel i7'],
                    ['RAM', 'texto', null, '16GB'],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Pulgadas, detalles del estado'],
                ],
                'Estabilizador de tensión' => [
                    ['Marca', 'texto', null, 'APC, CyberPower, etc.'],
                    ['Modelo', 'texto', null, 'Smart-UPS 1500, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Capacidad (VA)', 'texto', null, '1500'],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Impresora' => [
                    ['Marca', 'texto', null, 'Epson, HP, etc.'],
                    ['Modelo', 'texto', null, 'MFP-400, LaserJet 4014, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Tipo', 'select', ['Multifunción', 'Inyección de tinta', 'Láser', 'Térmica']],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Monitor' => [
                    ['Marca', 'texto', null, 'Dell, Samsung, etc.'],
                    ['Modelo', 'texto', null, 'U2419H, S24F350, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456, no visible'],
                    ['Tamaño (pulgadas)', 'texto', null, '24'],
                    ['Tipo', 'select', ['LCD', 'LED', 'Otro']],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Mouse' => [
                    ['Marca', 'texto', null, 'Logitech, Genius, etc.'],
                    ['Modelo', 'texto', null, 'MX Master 2S, Wireless Mouse 350, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Tipo', 'select', ['Cableado', 'Inalámbrico']],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Parlantes' => [
                    ['Marca', 'texto', null, 'Sony, JBL, etc.'],
                    ['Modelo', 'texto', null, 'SRS-XB300, SB-200, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Proyector' => [
                    ['Marca', 'texto', null, 'Epson, BenQ, etc.'],
                    ['Modelo', 'texto', null, 'PowerLite 83X, VH300, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Router' => [
                    ['Marca', 'texto', null, 'TP-Link, Netgear, etc.'],
                    ['Modelo', 'texto', null, 'Archer C7, TWR840, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Switch' => [
                    ['Marca', 'texto', null, 'Cisco, Netgear, etc.'],
                    ['Modelo', 'texto', null, 'Catalyst 9300, GS300, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Puertos', 'select', ['4', '8', '16', '24', '48']],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Tableta' => [
                    ['Marca', 'texto', null, 'Apple, Samsung, etc.'],
                    ['Modelo', 'texto', null, 'iPad, Galaxy Tab, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Color', 'texto'],
                    ['Tamaño (pulgadas)', 'texto', null, '10.1, 11, 12'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Teclado' => [
                    ['Marca', 'texto', null, 'DELL, Logitech, etc.'],
                    ['Modelo', 'texto', null, 'KB216, K120, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Color', 'texto'],
                    ['Tipo', 'select', ['Cableado', 'Inalámbrico']],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Teléfono' => [
                    ['Marca', 'texto', null, 'Cisco, Samsung, etc.'],
                    ['Modelo', 'texto', null, 'SPA504G, 7945, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Tipo', 'select', ['Fijo cableado', 'Fijo IP']],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Celular' => [
                    ['Marca', 'texto', null, 'Samsung, Apple, etc.'],
                    ['Modelo', 'texto', null, 'Galaxy S21, iPhone 13, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['IMEI', 'texto', null, 'Ej: 356938035643809'],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Televisor' => [
                    ['Marca', 'texto', null, 'Samsung, LG, etc.'],
                    ['Modelo', 'texto', null, 'UN55NU6900, 55UK6300, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Tamaño (pulgadas)', 'select', ['32', '55', '65', '75']],
                    ['Tipo', 'select', ['LCD', 'LED', 'Otro']],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'UPS' => [
                    ['Marca', 'texto', null, 'APC, CyberPower, etc.'],
                    ['Modelo', 'texto', null, 'Back-UPS ES 700, CP1500AVR, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Scanner' => [
                    ['Marca', 'texto', null, 'Epson, Canon, etc.'],
                    ['Modelo', 'texto', null, 'GT-S200, L220, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Tipo', 'select', ['Multifunción', 'Escaner de mesa', 'Otro']],
                    ['Color', 'texto'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
            ],
        ],
        'A4' => [
            'nombre' => 'Armamento, municiones y equipo de protección personal y balística',
            'elementos' => [
                'Armamento' => [
                    ['Tipo', 'select', ['Ametralladora', 'Fusil', 'Subfusil', 'Revólver', 'Pistola', 'Escopeta', 'Otro']],
                    ['Marca', 'texto', null, 'Glock, Bersa, Remington, etc.'],
                    ['Modelo', 'texto', null, 'Glock 17, ThunderPro, 870 Express, etc.'],
                    ['Tipo de carga', 'select', ['Semiautomática', 'Automática', 'Otro']],
                    ['Numeración', 'texto', null, 'SN123456'],
                    ['Calibre (MM)', 'texto', null, '9mm, .12, etc.'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Equipo de protección personal' => [
                    ['Tipo', 'select', ['Casco balístico', 'Auditiva', 'Visual y facial', 'Respiratoria', 'Manos y brazos', 'Prot. del cuerpo', 'Otro']],
                    ['Marca', 'texto', null, '3M, MSA, etc.'],
                    ['Modelo', 'texto', null, 'VestGuard, V-Gard, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456, No visible'],
                    ['Talla', 'texto', null, 'S, M, L, XL'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Equipo de protección balística' => [
                    ['Tipo', 'select', ['Chaleco antibalas', 'Placas balísticas', 'Otro']],
                    ['Marca', 'texto', null, '3M, MSA, etc.'],
                    ['Modelo', 'texto', null, 'VestGuard, V-Gard, etc.'],
                    ['Tipo de protección', 'select', ['RB1', 'RB2', 'RB3', 'RB4', 'RB5', 'RBE', 'Otro']],
                    ['Número de serie', 'texto', null, 'SN123456, No visible'],
                    ['Talla', 'texto', null, 'S, M, L, XL'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Fecha de fabricación', 'texto', null, '10/03/2021, Desconocido'],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Municiones' => [
                    ['Tipo', 'select', ['9mm', '.12', '.223', 'Otro']],
                    ['Marca', 'texto', null, 'Remington, Federal, etc.'],
                    ['Modelo', 'texto', null, 'M1911, M4, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Calibre (MM)', 'texto', null, '9mm, .12, etc.'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
            ],
        ],
        'A5' => [
            'nombre' => 'Máquinas y herramientas',
            'elementos' => [
                'Aspiradora' => [
                    ['Tipo', 'select', ['Inalámbrica', 'Cableada', 'Otro']],
                    ['Marca', 'texto', null, 'Dyson, Electrolux, etc.'],
                    ['Modelo', 'texto', null, 'V11, PowerMax, etc.'],
                    ['Número de serie', 'texto', null, 'SN123456'],
                    ['Potencia (W)', 'texto', null, '1000, 1500, etc.'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Bomba de agua' => [],
                'Compresor' => [],
                'Cortadora de césped' => [],
                'Tractor cortacésped' => [],
                'Desmalezadora' => [],
                'Generador eléctrico' => [],
                'Hidrolavadora' => [],
                'Motoguadaña' => [],
                'Motobomba' => [],
                'Motosierra' => [],
                'Pulidora' => [],
                'Sierra circular' => [],
            ],
        ],
        'A6' => [
            'nombre' => 'Vehículos',
            'elementos' => [
                'Automóvil' => [
                    ['Tipo', 'select', ['Sedán', 'Hatchback', 'Otro']],
                    ['Marca', 'texto', null, 'Fiat, Ford, etc.'],
                    ['Modelo', 'texto', null, 'Toro, Focus, etc.'],
                    ['Año', 'texto', null, '2020, 2021, etc.'],
                    ['Dominio', 'texto', null, 'ABC-123, XYZ-456, etc.'],
                    ['Color', 'texto', null, 'Rojo, Azul, etc.'],
                    ['Número de motor', 'texto', null, 'SN123456'],
                    ['Número de chasis', 'texto', null, '123456'],
                    ['Economía de consumo', 'select', ['Muy bueno', 'Bueno', 'Regular', 'Malo']],
                    ['Estado de funcionamiento', 'select', ['Servicio', 'Radiado', 'Fuera de servicio', 'Otro']],
                    ['Número de identificación', 'texto', null, 'SN123456'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Número de expediente', 'texto', null, 'EXP123456'],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Camioneta' => [
                    ['Tipo', 'select', ['PickUp', 'Otro']],
                    ['Marca', 'texto', null, 'Toyota, Ford, etc.'],
                    ['Modelo', 'texto', null, 'Hilux, Ranger, etc.'],
                    ['Año', 'texto', null, '2020, 2021, etc.'],
                    ['Dominio', 'texto', null, 'ABC-123, XYZ-456, etc.'],
                    ['Color', 'texto', null, 'Rojo, Azul, etc.'],
                    ['Número de motor', 'texto', null, 'SN123456'],
                    ['Número de chasis', 'texto', null, '123456'],
                    ['Economía de consumo', 'select', ['Muy bueno', 'Bueno', 'Regular', 'Malo']],
                    ['Estado de funcionamiento', 'select', ['Servicio', 'Radiado', 'Fuera de servicio', 'Otro']],
                    ['Número de identificación', 'texto', null, 'SN123456'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Número de expediente', 'texto', null, 'EXP123456'],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Camión' => [
                    ['Tipo', 'select', ['Camión liviano', 'Camión pesado', 'Otro']],
                    ['Marca', 'texto', null, 'Mercedes-Benz, Volvo, etc.'],
                    ['Modelo', 'texto', null, 'Actros, FH, etc.'],
                    ['Año', 'texto', null, '2020, 2021, etc.'],
                    ['Dominio', 'texto', null, 'ABC-123, XYZ-456, etc.'],
                    ['Color', 'texto', null, 'Rojo, Azul, etc.'],
                    ['Número de motor', 'texto', null, 'SN123456'],
                    ['Número de chasis', 'texto', null, '123456'],
                    ['Economía de consumo', 'select', ['Muy bueno', 'Bueno', 'Regular', 'Malo']],
                    ['Estado de funcionamiento', 'select', ['Servicio', 'Radiado', 'Fuera de servicio', 'Otro']],
                    ['Número de identificación', 'texto', null, 'SN123456'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Número de expediente', 'texto', null, 'EXP123456'],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Minibus' => [
                    ['Tipo', 'select', ['Minibus', 'Microbus', 'Otro']],
                    ['Marca', 'texto', null, 'Mercedes-Benz, Volkswagen, etc.'],
                    ['Modelo', 'texto', null, 'Sprinter, Kombi, etc.'],
                    ['Año', 'texto', null, '2020, 2021, etc.'],
                    ['Dominio', 'texto', null, 'ABC-123, XYZ-456, etc.'],
                    ['Color', 'texto', null, 'Rojo, Azul, etc.'],
                    ['Número de motor', 'texto', null, 'SN123456'],
                    ['Número de chasis', 'texto', null, '123456'],
                    ['Economía de consumo', 'select', ['Muy bueno', 'Bueno', 'Regular', 'Malo']],
                    ['Estado de funcionamiento', 'select', ['Servicio', 'Radiado', 'Fuera de servicio', 'Otro']],
                    ['Número de identificación', 'texto', null, 'SN123456'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Número de expediente', 'texto', null, 'EXP123456'],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Motovehículo' => [
                    ['Tipo', 'select', ['Scooter', 'Enduro', 'Cruiser', 'Otro']],
                    ['Marca', 'texto', null, 'Yamaha, Honda, etc.'],
                    ['Modelo', 'texto', null, 'R1, CBR, etc.'],
                    ['Año', 'texto', null, '2020, 2021, etc.'],
                    ['Dominio', 'texto', null, 'ABC-123, XYZ-456, etc.'],
                    ['Color', 'texto', null, 'Rojo, Azul, etc.'],
                    ['Número de motor', 'texto', null, 'SN123456'],
                    ['Número de chasis', 'texto', null, '123456'],
                    ['Economía de consumo', 'select', ['Muy bueno', 'Bueno', 'Regular', 'Malo']],
                    ['Estado de funcionamiento', 'select', ['Servicio', 'Radiado', 'Fuera de servicio', 'Otro']],
                    ['Número de identificación', 'texto', null, 'SN123456'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Número de expediente', 'texto', null, 'EXP123456'],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Utilitario' => [
                    ['Tipo', 'select', ['Furgón', 'PickUp', 'Otro']],
                    ['Marca', 'texto', null, 'Fiat, Ford, etc.'],
                    ['Modelo', 'texto', null, 'Trek, Explorer, etc.'],
                    ['Año', 'texto', null, '2020, 2021, etc.'],
                    ['Dominio', 'texto', null, 'ABC-123, XYZ-456, etc.'],
                    ['Color', 'texto', null, 'Rojo, Azul, etc.'],
                    ['Número de motor', 'texto', null, 'SN123456'],
                    ['Número de chasis', 'texto', null, '123456'],
                    ['Economía de consumo', 'select', ['Muy bueno', 'Bueno', 'Regular', 'Malo']],
                    ['Estado de funcionamiento', 'select', ['Servicio', 'Radiado', 'Fuera de servicio', 'Otro']],
                    ['Número de identificación', 'texto', null, 'SN123456'],
                    ['Procedencia', 'select', ['Adquirido', 'Donado', 'Otro']],
                    ['Número de expediente', 'texto', null, 'EXP123456'],
                    ['Observaciones', 'textarea', null, 'Detalles del estado'],
                ],
                'Van' => [],
                'Otros' => [],
            ],
        ],
        'A7' => [
            'nombre' => 'Altas',
            'elementos' => [
                'Por donación' => [
                    ['Fecha de alta', 'texto', null, '10/03/2021'],
                    ['Número de expediente', 'texto', null, 'EXP123456'],
                    ['Descripción del bien', 'texto', null, 'Descripción detallada del bien dado de alta'],
                    ['Categoría destino', 'select', ['A1', 'A2', 'A3', 'A4', 'A5', 'A6']],
                    ['Observaciones', 'textarea', null, 'Detalles adicionales sobre el alta del bien'],
                ],
                'Por compra' => [
                    ['Fecha de alta', 'texto', null, '10/03/2021'],
                    ['Número de expediente', 'texto', null, 'EXP654321'],
                    ['Descripción del bien', 'texto', null, 'Descripción detallada del bien comprado'],
                    ['Categoría destino', 'select', ['A1', 'A2', 'A3', 'A4', 'A5', 'A6']],
                    ['Observaciones', 'textarea', null, 'Detalles adicionales sobre el alta del bien'],
                ],
                'Por transferencia' => [],
            ],
        ],
        'A8' => [
            'nombre' => 'Bajas',
            'elementos' => [
                'Por donación' => [
                    ['Fecha de baja', 'texto', null, '15/04/2021'],
                    ['Motivo de la baja', 'texto', null, 'Motivo detallado'],
                    ['Categoría origen', 'select', ['A1', 'A2', 'A3', 'A4', 'A5', 'A6']],
                    ['Observaciones', 'textarea', null, 'Detalles adicionales sobre la baja'],
                ],
                'Por transferencia' => [
                    ['Fecha de baja', 'texto', null, '15/04/2021'],
                    ['Motivo de la baja', 'texto', null, 'Motivo detallado'],
                    ['Categoría origen', 'select', ['A1', 'A2', 'A3', 'A4', 'A5', 'A6']],
                    ['Observaciones', 'textarea', null, 'Detalles adicionales sobre la baja'],
                ],
                'Por obsolescencia' => [
                    ['Fecha de baja', 'texto', null, '15/04/2021'],
                    ['Motivo de la baja', 'texto', null, 'Motivo detallado'],
                    ['Categoría origen', 'select', ['A1', 'A2', 'A3', 'A4', 'A5', 'A6']],
                    ['Observaciones', 'textarea', null, 'Detalles adicionales sobre la baja'],
                ],
            ],
        ],
    ];

    public function run(): void
    {
        foreach (self::ELEMENTOS as $codigo => $config) {
            $categoria = Categoria::where('codigo', $codigo)->first();
            if (!$categoria) {
                continue;
            }

            $orden = 0;
            foreach ($config['elementos'] as $nombreElemento => $camposDef) {
                $tipo = TipoItem::firstOrCreate(
                    ['categoria_id' => $categoria->id, 'nombre' => $nombreElemento],
                    ['orden' => $orden]
                );

                $tipo->campos()->delete();

                foreach ($camposDef as $i => $campoDef) {
                    [$nombre, $tipoCampo, $opciones, $placeholder] = array_pad($campoDef, 4, null);

                    CampoDinamico::create([
                        'categoria_id' => $categoria->id,
                        'tipo_item_id' => $tipo->id,
                        'nombre' => $nombre,
                        'tipo' => $tipoCampo,
                        'opciones' => $opciones,
                        'placeholder' => $placeholder,
                        'requerido' => $nombre !== 'Observaciones',
                        'activo' => true,
                        'orden' => $i,
                    ]);
                }

                $orden++;
            }
        }
    }
}